/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TIPIv4;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sergio Novais
 */
public class TabelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TabelaProduto
     */
    public TabelaProduto() {
        initComponents();
        setLocationRelativeTo(null);
        updateGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boxNcm = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        lblmensagem = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAliq = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabela de Produtos");

        tblProdutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Produto", "NCM", "Valor", "Alíquota"
            }
        ));
        tblProdutos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Cadastro de Produtos com NCM");

        boxNcm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0000.00.00", "0301.10.01", "0510.11.00", "2988.99.99" }));

        jLabel3.setText("Valor:");

        btnCriar.setText("Criar Item");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        lblmensagem.setForeground(new java.awt.Color(255, 0, 0));

        jLabel4.setText("Alíquota:");

        jLabel1.setText("Nome do Produto:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("NCM:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAliq, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxNcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAliq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnDeletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblmensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        //lblmensagem.setText("");
        if(!txtNome.getText().trim().equals("")){ // precisei colocar a ! para funcionar
            Produto prod = new Produto();
            prod.setNome(txtNome.getText());
            prod.setValor(txtValor.getText());
            prod.setNcm(boxNcm.getSelectedItem().toString());
            prod.setAliq(txtAliq.getText());
            salvaNoArquivo(prod);
            JOptionPane.showMessageDialog(null, "Item criado com sucesso!");
            updateGrid();
        }else{
            //lblmensagem.setText("Nome do produto em branco!");
            JOptionPane.showMessageDialog(null, "Nome do produto em branco!");
        }
    }//GEN-LAST:event_btnCriarActionPerformed
    
    public void updateGrid(){
        limpaGrid();
        try {
            String caminhoAbsoluto = new File("").getAbsolutePath();
            FileReader fr = new FileReader(caminhoAbsoluto + "\\produtos.txt");
            BufferedReader reader = new BufferedReader(fr);
            String linha = reader.readLine();
            while (linha != null) {
                //[nome][ncm][valor][aliq]
                String[] dados = linha.split("!@!");
                Produto prod = new Produto();
                prod.setNome(dados[0]);
                prod.setNcm(dados[1]);
                prod.setValor(dados[2]);
                prod.setAliq(dados[3]);
                
                escreveNaGrid(prod);
                linha = reader.readLine();
            }

        } catch (Exception e) {
            System.out.println("erro na leitura");
        }
    }
    
    public void limpaGrid(){
        DefaultTableModel tabela= (DefaultTableModel)tblProdutos.getModel();
        int count = tabela.getRowCount();
        for (int i = count; i > 0; i--) {
            tabela.removeRow(i-1);
        }
        tblProdutos.setModel(tabela);
    }
    
    public void escreveNaGrid(Produto prd){
        
        DefaultTableModel tabela=(DefaultTableModel)tblProdutos.getModel(); // tirar dúvidas sobre a estrutura do default
        tabela.addRow(new Object[]{prd.getNome(),prd.getNcm(),prd.getValor(),prd.getAliq()}); // cria uma nova linha no vetor de objetos e pega os dados inseridos nos campos
            
    }
    
    public void salvaNoArquivo(Produto prd){
        try {
            String breakline = System.getProperty("line.separator");
            String caminhoAbsoluto = new File("").getAbsolutePath();
            FileWriter escritor = new FileWriter(caminhoAbsoluto + "\\produtos.txt", true);
            escritor.write(prd.getNome() + "!@!" + prd.getNcm() + "!@!" + prd.getValor() + "!@!" + prd.getAliq());
            escritor.write(breakline);
            escritor.close();
        } catch (Exception e) {
            System.out.println("Erro na escrita do arquivo");
            e.printStackTrace();
        }
    }
    
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        lblmensagem.setText("");
        DefaultTableModel tabela=(DefaultTableModel) tblProdutos.getModel();
        if(tblProdutos.getSelectedRow()==-1){
            if(tblProdutos.getRowCount()==0){
                lblmensagem.setText("Tabela sem produtos cadastrados!");
                JOptionPane.showMessageDialog(null, "Tabela sem produtos cadastrados!");
            }else{
                lblmensagem.setText("Selecione um produto para atualizar!");
                JOptionPane.showMessageDialog(null, "Selecione um produto para atualizar");
            }
        }else{
            //1 - ler a lista que na ta no arquivo
            List<Produto> produtos = lerLista();
            //2 - atualiza linha da lista criando um novo objeto e substituindo pelo antigo
            Produto prod = new Produto();
            prod.setNome(txtNome.getText());
            prod.setNcm(boxNcm.getSelectedItem().toString());
            prod.setValor(txtValor.getText());
            prod.setAliq(txtAliq.getText());
            int i = tblProdutos.getSelectedRow();
            produtos.set(i,prod);
            
//            tabela.setValueAt(txtNome.getText(), tblProdutos.getSelectedRow(), 0); // os números são posição no vetor
//            tabela.setValueAt(boxNcm.getSelectedItem().toString(), tblProdutos.getSelectedRow(), 1); // os números são posição no vetor
//            tabela.setValueAt(txtValor.getText(),tblProdutos.getSelectedRow(), 2); // os números são posição no vetor
//            tabela.setValueAt(txtAliq.getText(), tblProdutos.getSelectedRow(), 3); // os números são posição no vetor
            //3.1 - limpa arquivo
            limpaArquivo();
            //3.2 - escreve um por um
            for (Produto produto : produtos) {
                salvaNoArquivo(produto);
            }
            //4 - update grid
            updateGrid();
            JOptionPane.showMessageDialog(null, "Item atualizado com sucesso!");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        DefaultTableModel tabela=(DefaultTableModel) tblProdutos.getModel();
        txtNome.setText(tabela.getValueAt(tblProdutos.getSelectedRow(), 0).toString());
        boxNcm.setSelectedItem(tabela.getValueAt(tblProdutos.getSelectedRow(), 1).toString());
        txtValor.setText(tabela.getValueAt(tblProdutos.getSelectedRow(), 2).toString());
        txtAliq.setText(tabela.getValueAt(tblProdutos.getSelectedRow(), 3).toString());
    }//GEN-LAST:event_tblProdutosMouseClicked

    public void limpaArquivo(){
        try {
            String breakline = System.getProperty("line.separator");
            String caminhoAbsoluto = new File("").getAbsolutePath();
            FileWriter escritor = new FileWriter(caminhoAbsoluto + "\\produtos.txt", false);
            escritor.write("");
            escritor.close();
        } catch (Exception e) {
            System.out.println("Erro na escrita do arquivo");
            e.printStackTrace();
        }
    }
    
    public List<Produto> lerLista(){
        List<Produto> produtos = new ArrayList<>();
        try {
            String caminhoAbsoluto = new File("").getAbsolutePath();
            FileReader fr = new FileReader(caminhoAbsoluto + "\\produtos.txt");
            BufferedReader reader = new BufferedReader(fr);
            String linha = reader.readLine();
            Produto prod;
            while (linha != null) {
                //[nome][ncm][valor][aliq]
                String[] dados = linha.split("!@!");
                prod = new Produto();
                prod.setNome(dados[0]);
                prod.setNcm(dados[1]);
                prod.setValor(dados[2]);
                prod.setAliq(dados[3]);
                produtos.add(prod);
                linha = reader.readLine();
            }

        } catch (Exception e) {
            System.out.println("erro na leitura da lista");
        }
        return produtos;
    }
    
    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        DefaultTableModel tabela=(DefaultTableModel) tblProdutos.getModel();
        if(tblProdutos.getSelectedRow()==-1){
            if(tblProdutos.getRowCount()==0){
                lblmensagem.setText("Tabela sem produtos cadastrados!");
                JOptionPane.showMessageDialog(null, "Tabela sem produtos cadastrados!");
            }else{
                lblmensagem.setText("Selecione um produto para deletar!");
                JOptionPane.showMessageDialog(null, "Selecione um produto para deletar");
            }
        }else{
            //tabela.removeRow(tblProdutos.getSelectedRow());
            //1 - ler a lista que na ta no arquivo
            List<Produto> produtos = lerLista();
            //2 - remove linha da lista
            produtos.remove(tblProdutos.getSelectedRow());
            //3.1 - limpa arquivo
            limpaArquivo();
            //3.2 - escreve um por um
            for (Produto produto : produtos) {
                salvaNoArquivo(produto);
            }
            //4 - update grid
            updateGrid();
            JOptionPane.showMessageDialog(null, "Item excluído com sucesso!");
            
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TabelaProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaProduto().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNcm;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmensagem;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtAliq;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
